### ISSUE TITLE
403 invalid signature when accepting invitation 

### ISSUE THREAD

**Issue by gensi0** [deck9/input#131]
Hi ! :wave: 

First of all, thank you for this wonderfull project. I've been setting it up with docker and so far it's pretty easy !

The only issue I have now is when sending a Team invitation. First I add a team member and he receives the email with no issue. Then he's able to create an account but when he clicks on the second link "Accept Invitation". He gets this page : 

![image](https://github.com/deck9/input/assets/71636603/dceed06a-05cc-415c-9810-833fa8a5e627)

Container wise the only thing I can see is : 

```shell
input  | 192.168.x.x - - [06/Feb/2024:15:25:48 +0000] "GET /team-invitations/1?signature=e4366e1f9f4b8fe69ed1c55be8b9067080xxxx3c06ba4c0f6a90a5c7ec6bb754 HTTP/1.0" 403 6612 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" "-" 0.036 0.036 . -
```

(I replaced some part of the signature with xxxx because I don't know if it's sensitive info)

My docker-compose.yml looks like : 

```yml
version: "3"
services:
  input:
    image: ghcr.io/deck9/input:main
    container_name: input
    ports:
      - "192.168.x.x:8081:80"
    volumes:
      - input-data:/var/www/html/storage
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      APP_URL: https://myfqdn
      MAIL_FROM_ADDRESS: postmaster@myfqdn
      MAIL_FROM_NAME: myfqdn
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.mailgun.org
      MAIL_PORT: 465
      MAIL_ENCRYPTION: tls
      MAIL_USERNAME: postmaster@myfqdn
      MAIL_PASSWORD: xxxxx

volumes:
  input-data:
```

The only modification made to the default nginx is disabling ipv6 support.

And I have a simple nginx server for https reverse proxy.

Is there anything I'm missing ?

Thank you for your time !
