### ISSUE TITLE
"Send email notifications" causing AxiosError (500) behind Cloudflare Tunnel

### ISSUE THREAD

**Issue by wesleysinks** [deck9/input#137]
I'm unable to get email notifications to work using the SMTP env variables. Perhaps I'm doing something incorrect. I'm running this stack via Portainer behind Cloudflare Tunnel. Forms work and go through to completion page as expected until I enable "Send email notifications"

docker-compose.yaml

```yaml
version: "3"
services:
    input:
        ports:
            - 8070:8080
        container_name: input
        volumes:
            - input-data:/var/www/html/storage
        environment:
            - APP_URL=https://forms.soloist.systems
            - MAIL_MAILER=smtp
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_USERNAME=${MAIL_USER}
            - MAIL_PASSWORD=${MAIL_PASS}
            - MAIL_PORT=587
            - MAIL_ENCRYPTION=tls
        image: ghcr.io/deck9/input:main
volumes:
    input-data:
        name: input-data
```

stack.env (Portainer - credentials redacted)

```
MAIL_HOST="smtppro.zoho.com"
MAIL_USER="email@host.com"
MAIL_PASS="*****"
```

log file from Chromium

```
classic.js:805 
        
        
       POST https://forms.soloist.systems/api/public/forms/jY85 500 (Internal Server Error)
(anonymous) @ classic.js:805
xhr @ classic.js:805
ju @ classic.js:807
Promise.then (async)
_request @ classic.js:808
request @ classic.js:807
(anonymous) @ classic.js:808
(anonymous) @ classic.js:803
(anonymous) @ classic.js:808
await in (anonymous) (async)
O6 @ classic.js:808
next @ classic.js:808
(anonymous) @ classic.js:22
b @ classic.js:812
(anonymous) @ classic.js:812
(anonymous) @ classic.js:811
classic.js:812 Uncaught (in promise) ce {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_RESPONSE"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}adapter: (2) ['xhr', 'http']data: "{\"token\":\"zcdKJ32xMXof1hYmPT7X9r8DVrNIInNl\",\"payload\":{\"j2W4\":{\"payload\":\"wesley@wsle.me\",\"actionId\":\"jR\"}}}"env: {FormData: ƒ, Blob: ƒ}headers: Vi {Accept: 'application/json', Content-Type: 'application/json', X-Requested-With: 'XMLHttpRequest', X-XSRF-TOKEN: 'eyJpdiI6IndHSnRQQlpLR3JGdFE0b1ptRE9rV3c9PSIsInZhbH…xNzlmYjU4YmE2MGU0NWMzYjVlNWJkNGZhIiwidGFnIjoiIn0='}maxBodyLength: -1maxContentLength: -1method: "post"timeout: 0transformRequest: [ƒ]transformResponse: [ƒ]transitional: {silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}url: "https://forms.soloist.systems/api/public/forms/jY85"validateStatus: ƒ (t)withCredentials: truexsrfCookieName: "XSRF-TOKEN"xsrfHeaderName: "X-XSRF-TOKEN"[[Prototype]]: Objectmessage: "Request failed with status code 500"name: "AxiosError"request: XMLHttpRequestonabort: ƒ ()onerror: ƒ ()onload: nullonloadend: ƒ g()onloadstart: nullonprogress: nullonreadystatechange: nullontimeout: ƒ ()readyState: 4response: "{\n    \"message\": \"Server Error\"\n}"responseText: "{\n    \"message\": \"Server Error\"\n}"responseType: ""responseURL: "https://forms.soloist.systems/api/public/forms/jY85"responseXML: nullstatus: 500statusText: ""timeout: 0upload: XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}withCredentials: true[[Prototype]]: XMLHttpRequestresponse: config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}data: {message: 'Server Error'}headers: Vi {access-control-allow-credentials: 'true', access-control-allow-origin: 'https://forms.soloist.systems', alt-svc: 'h3=":443"; ma=86400', cache-control: 'no-cache, private', cf-cache-status: 'DYNAMIC', …}request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}status: 500statusText: ""[[Prototype]]: Objectstack: "AxiosError: Request failed with status code 500\n    at ky (https://forms.soloist.systems/js/classic.js:805:1045)\n    at XMLHttpRequest.g (https://forms.soloist.systems/js/classic.js:805:4237)\n    at fi.request (https://forms.soloist.systems/js/classic.js:807:3114)\n    at async https://forms.soloist.systems/js/classic.js:808:24085"[[Prototype]]: Errorconstructor: ƒ ce(e,t,n,r,a)toJSON: ƒ ()isAxiosError: true[[Prototype]]: Object
b @ classic.js:812
await in b (async)
(anonymous) @ classic.js:812
(anonymous) @ classic.js:811
jY85:1 
        
        
       POST https://forms.soloist.systems/api/public/forms/jY85 500 (Internal Server Error)
```
